# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zeriff
logo: logo.png
wlogo: whitelogo.png

url:  "http://zeriff.com"
# url: "http://localhost:4000" # the base hostname & protocol for your site

owner:
  name: Zeriff Raiments

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Shop
    url: /shop/home
  - title: Blog
    url: /#indexposts
#  - title: Featured Posts
#    url: /featured
#  - title: Categories
#    url: /categories
#  - title: About
#    url: /about

gems: [jekyll-paginate]
# Build settings
markdown: kramdown
theme: minima
paginate:    5
paginate_path: /page:num
